### PR TITLE
Add NegativePasswordLoginTest and necessary DataProvider

### PR DESCRIPTION
**Pull request by EduardNastych**
## Pull Request description

Add NegativePasswordLoginTest and necessary DataProvider

## General checklist

- [x] No merge conflicts
- [x] No commented blocks of code
- [x] No code formatting issues.
- [x] No wildcart imports
- [x] Description contains human-readable scope of changes.

### CODE REVIEW

**Review by KolyaSamandasiuk — APPROVED** [review]

**Review by KolyaSamandasiuk — APPROVED** [review]
good

**Review by KolyaSamandasiuk — CHANGES_REQUESTED** [review]
goood

**Review by maksKondr — APPROVED** [review]
ok

**Review by KolyaSamandasiuk — APPROVED** [review]
ok1

**Pull request merged**
